# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Netresearch DTT GmbH
extends: default

ignore:
  - "skills/*/examples/"

rules:
  line-length: disable
  truthy: disable
  document-start: disable
